/** Public URLs for environment GLBs (served from /public). */
export const ENV_MODELS = {
  trainHead: "/images/environments/train-electric-square-a.glb",
  trainCar: "/images/environments/train-electric-square-b.glb",
  trainTail: "/images/environments/train-electric-square-c.glb",
  railStraight: "/images/environments/railroad-straight.glb",
  railCrossing: "/images/environments/railroad-crossing.glb",
  railCrossingLong: "/images/environments/railroad-crossing-long.glb",
  bench: "/images/environments/bench.gltf",
  trashcan: "/images/environments/trashcan.gltf",
  tree: "/images/environments/tree.gltf",
  treeLarge: "/images/environments/tree_large.gltf",
  streetLantern: "/images/environments/street_lantern.gltf",
  railroadStraight: "/images/environments/railroad-straight.glb",
  bushLarge: "/images/environments/bush_large.gltf",
  bush: "/images/environments/bush.gltf",
  cobbleStone: "/images/environments/cobble_stones.gltf",
  cobbleStoneLarge: "/images/environments/cobble_stones_large.gltf",
  flowerA: "/images/environments/flower_a.gltf",
  flowerB: "/images/environments/flower_b.gltf",
  grassA: "/images/environments/grass_a.gltf",
  grassB: "/images/environments/grass_b.gltf",
  hedgeStraight: "/images/environments/hedge_straight.gltf",
  hedgeStraightLong: "/images/environments/hedge_straight_long.gltf",
  hedgeCorner: "/images/environments/hedge_corner.gltf",
  vendingMachine: "/images/environments/vending_machine.glb",
  railing: "/images/environments/railing2.glb",
};

export const ENV_MODEL_URLS = Object.values(ENV_MODELS);
